name: Test

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  build:

    timeout-minutes: 5

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Wait
      if: github.event_name != 'watch'
      run: |
        random_time=7
        echo "等待 ${random_time} 分钟后开始执行"
        for((i=1;i<=${random_time};i++));  
        do
        echo "倒计时:剩余 $[${random_time}-$i] 分钟"
        sleep 1m
        done
